spring:
    application:
        name: auth-security-system

    config:
        import:
            - classpath:/application-db.yml
            - classpath:/application-jwt.yml
            - optional:file:.env[.properties]

    output:
        ansi:
            enabled: ALWAYS
